const maleHair = [
    'Kel',
    'Kısa Saç 1',
    'Kısa Saç 2',
    'Traşlı Kısa Saç 1',
    'Kısa Saç 3',
    'Dağınık Kısa Saç',
    'Dağınık Traşlı Saç',
    'At Kuyruğu',
    'Rasta Saç Modeli 1',
    'Kıvırcık Kıas Saç',
    'Kısa Saç 4',
    'Kısa Dik Saç',
    'Kısa Saç 5',
    'Dağınık Uzun Saç 1',
    'Rasta Uzun Saç',
    'Düz Uzun Saç 1',
    'Kıvırcık Uzun Saç',
    'Düz Uzun Saç 2',
    'Kısa Saç 6',
    'Düz Uzun Saç 2',
    'Traşlı Kısa Saç',
    'Presley Saç Modeli 1',
    'Presley Saç Modeli 2',
    'Presley Saç Modeli 3',
    'Rasta Saç Modeli 2',
    'Rasta Saç Modeli 3',
    'Rasta Saç Modeli 3',
    'Rasta Saç Modeli 4',
    'Rasta Saç Modeli 5',
    'Rasta Saç Modeli 6',
    'Kısa Presley Modeli',
    'Orta Uzun Saç',
    'Traşlı Kısa Saç 2',
    'Traşlı Kısa Saç 3',
    'Diken Modeli Saç',
    'Dağınık Uzun Saç 2',
    'Ayrımlı Uzun Saç',
    'Kısa Saç 1',
    'Kısa Saç 2',
    'Traşlı Kısa Saç 1',
    'Kısa Saç 3',
    'Dağınık Kısa Saç',
    'Dağınık Traşlı Saç',
    'At Kuyruğu',
    'Rasta Saç Modeli 1',
    'Kıvırcık Kıas Saç',
    'Kısa Saç 4',
    'Kısa Dik Saç',
    'Kısa Saç 5',
    'Dağınık Uzun Saç 1',
    'Rasta Saç Modeli 1',
    'Ayrımlı Uzun Saç 2',
    'Kıvırcık Saç Modeli',
    'Uzun Saç 2',
    'Kısa Saç 6',
    'Kısa Saç 7',
    'Uzun Saç 3',
    'Traşlı Kısa Saç 2',
    'Presley Saç Modeli',
    'Rasta Saç Modeli 2',
    'Rasta Saç Modeli 3',
    'Rasta Saç Modeli 4',
    'Rasta Saç Modeli 5',
    'Rasta Saç Modeli 6',
    'Rasta Saç Modeli 7',
    'Presley Modeli 2',
    'Uzun Saç 4',
    'Traşlı Kısa Saç 2',
    'Traşlı Kısa Saç 3',
    'Mohawk',
    'Diken Saç Modeli',
    'Dağınık Uzun Saç',
    'Ayrımlı Uzun Saç 2',
    'Dik Kısa Saç 2',
    'Traşlı Kısa Saç 4',
    'LSC Yeni Saç 1',
    'LSC Yeni Saç 2',
    'LSC Yeni Saç 3',
    'LSC Yeni Saç 4',
    'LSC Yeni Saç 5',
    'LSC Yeni Saç 6',
    'LSC Yeni Saç 7',
    'LSC Yeni Saç 8',
    'LSC Yeni Saç 9',
    'LSC Yeni Saç 10',
    'LSC Yeni Saç 11',
    'LSC Yeni Saç 12',
    'LSC Yeni Saç 13',
    'LSC Yeni Saç 14',
    'LSC Yeni Saç 15',
    'LSC Yeni Saç 16',
    'LSC Yeni Saç 17',
    'LSC Yeni Saç 18',
    'LSC Yeni Saç 19',
    'LSC Yeni Saç 20',
    'LSC Yeni Saç 21',
    'LSC Yeni Saç 22',
    'LSC Yeni Saç 23',
    'LSC Yeni Saç 24',
    'LSC Yeni Saç 25',
    'LSC Yeni Saç 26',
    'LSC Yeni Saç 27',
    'LSC Yeni Saç 28',
    'LSC Yeni Saç 29',
    'LSC Yeni Saç 30',
    'LSC Yeni Saç 31',
    'LSC Yeni Saç 32',
    'LSC Yeni Saç 33',
    'LSC Yeni Saç 34',
    'LSC Yeni Saç 35',
    'LSC Yeni Saç 36',
    'LSC Yeni Saç 37',
    'LSC Yeni Saç 38',
    'LSC Yeni Saç 39',
    'LSC Yeni Saç 40',
    'LSC Yeni Saç 41',
    'LSC Yeni Saç 42',
    'LSC Yeni Saç 43',
    'LSC Yeni Saç 44',
    'LSC Yeni Saç 45',
    'LSC Yeni Saç 46',
    'LSC Yeni Saç 47',
    'LSC Yeni Saç 48',
    'LSC Yeni Saç 49',
    'LSC Yeni Saç 50',
    'LSC Yeni Saç 51',
    'LSC Yeni Saç 52',
    'LSC Yeni Saç 53',
    'LSC Yeni Saç 54',
    'LSC Yeni Saç 55',
    'LSC Yeni Saç 56',
    'LSC Yeni Saç 57',
    'LSC Yeni Saç 58',
    'LSC Yeni Saç 59',
    'LSC Yeni Saç 60',
    'LSC Yeni Saç 61',
    'LSC Yeni Saç 62',
    'LSC Yeni Saç 63',
    'LSC Yeni Saç 64',
    'LSC Yeni Saç 65',
    'LSC Yeni Saç 66',
    'LSC Yeni Saç 67',
    'LSC Yeni Saç 68',
    'LSC Yeni Saç 69',
    'LSC Yeni Saç 70',
    'LSC Yeni Saç 71',
    'LSC Yeni Saç 72',
    'LSC Yeni Saç 73',
    'LSC Yeni Saç 74',
    'LSC Yeni Saç 75',
    'LSC Yeni Saç 76',
    'LSC Yeni Saç 77',
    'LSC Yeni Saç 78',
    'LSC Yeni Saç 79',
    'LSC Yeni Saç 80',
    'LSC Yeni Saç 81',
    'LSC Yeni Saç 82',
    'LSC Yeni Saç 83',
    'LSC Yeni Saç 84',
    'LSC Yeni Saç 85',
    'LSC Yeni Saç 86',
    'LSC Yeni Saç 87',
    'LSC Yeni Saç 88',
    'LSC Yeni Saç 89',
    'LSC Yeni Saç 90',
    'LSC Yeni Saç 91',
    'LSC Yeni Saç 92',
    'LSC Yeni Saç 93',
    'LSC Yeni Saç 94',
    'LSC Yeni Saç 95',
    'LSC Yeni Saç 96',
    'LSC Yeni Saç 97',
    'LSC Yeni Saç 98',
    'LSC Yeni Saç 99',
    'LSC Yeni Saç 100',
    'LSC Yeni Saç 101',
    'LSC Yeni Saç 102',
    'LSC Yeni Saç 103',
    'LSC Yeni Saç 104',
    'LSC Yeni Saç 105',
    'LSC Yeni Saç 106',
    'LSC Yeni Saç 107',
    'LSC Yeni Saç 108',
    'LSC Yeni Saç 109',
    'LSC Yeni Saç 110',
    'LSC Yeni Saç 111',
    'LSC Yeni Saç 112',
    'LSC Yeni Saç 113',
    'LSC Yeni Saç 114',
    'LSC Yeni Saç 115',
    'LSC Yeni Saç 116',
    'LSC Yeni Saç 117',
    'LSC Yeni Saç 118',
    'LSC Yeni Saç 119',
    'LSC Yeni Saç 120',
    'LSC Yeni Saç 121',
    'LSC Yeni Saç 122',
    'LSC Yeni Saç 123',
    'LSC Yeni Saç 124',
    'LSC Yeni Saç 125',
    'LSC Yeni Saç 126',
    'LSC Yeni Saç 127', 
    'LSC Yeni Saç 128',
    'LSC Yeni Saç 129',
    "LSC Yeni Saç 130",
    "LSC Yeni Saç 131",
    "LSC Yeni Saç 132",
    "LSC Yeni Saç 133",
    "LSC Yeni Saç 134",
    "LSC Yeni Saç 135",
    "LSC Yeni Saç 136",
    "LSC Yeni Saç 137",
    "LSC Yeni Saç 138",
    "LSC Yeni Saç 139",
    "LSC Yeni Saç 140",
    "LSC Yeni Saç 141",
    "LSC Yeni Saç 142",
    "LSC Yeni Saç 143",
    "LSC Yeni Saç 144",
    "LSC Yeni Saç 145",
    "LSC Yeni Saç 146",
    "LSC Yeni Saç 147",
    "LSC Yeni Saç 148",
    "LSC Yeni Saç 149",
    "LSC Yeni Saç 150",
    "LSC Yeni Saç 151",
    "LSC Yeni Saç 152",
    "LSC Yeni Saç 153",
    "LSC Yeni Saç 154",
    "LSC Yeni Saç 155",
    "LSC Yeni Saç 156",
    "LSC Yeni Saç 157",
    "LSC Yeni Saç 158",
    "LSC Yeni Saç 159",
    "LSC Yeni Saç 160",
    "LSC Yeni Saç 161",
    "LSC Yeni Saç 162",
    "LSC Yeni Saç 163",
    "LSC Yeni Saç 164",
    "LSC Yeni Saç 165",
    "LSC Yeni Saç 166",
    "LSC Yeni Saç 167",
    "LSC Yeni Saç 168",
    "LSC Yeni Saç 169",
    "LSC Yeni Saç 170",
    "LSC Yeni Saç 171",
    "LSC Yeni Saç 172",
    "LSC Yeni Saç 173",
    "LSC Yeni Saç 174",
    "LSC Yeni Saç 175",
    "LSC Yeni Saç 176",
    "LSC Yeni Saç 177",
    "LSC Yeni Saç 178",
    "LSC Yeni Saç 179",
    "LSC Yeni Saç 180",
    "LSC Yeni Saç 181",
    "LSC Yeni Saç 182",
    "LSC Yeni Saç 183",
    "LSC Yeni Saç 184",
    "LSC Yeni Saç 185",
    "LSC Yeni Saç 186",
    "LSC Yeni Saç 187",
    "LSC Yeni Saç 188",
    "LSC Yeni Saç 189",
    "LSC Yeni Saç 190",
    "LSC Yeni Saç 191",
    "LSC Yeni Saç 192",
    "LSC Yeni Saç 193",
    "LSC Yeni Saç 194",
    "LSC Yeni Saç 195",
    "LSC Yeni Saç 196",
    "LSC Yeni Saç 197",
    "LSC Yeni Saç 198",
    "LSC Yeni Saç 199",
    "LSC Yeni Saç 200",
    "LSC Yeni Saç 201",
    "LSC Yeni Saç 202",
    "LSC Yeni Saç 203",
    "LSC Yeni Saç 204",
    "LSC Yeni Saç 205",
    "LSC Yeni Saç 206",
    "LSC Yeni Saç 207",
    "LSC Yeni Saç 208",
    "LSC Yeni Saç 209",
    "LSC Yeni Saç 210",
    "LSC Yeni Saç 211",
    "LSC Yeni Saç 212",
    "LSC Yeni Saç 213",
    "LSC Yeni Saç 214",
    "LSC Yeni Saç 215",
    "LSC Yeni Saç 216",
    "LSC Yeni Saç 217",
    "LSC Yeni Saç 218",
    "LSC Yeni Saç 219",
    "LSC Yeni Saç 220",
    "LSC Yeni Saç 221",
    "LSC Yeni Saç 222",
    "LSC Yeni Saç 223",
    "LSC Yeni Saç 224",
    "LSC Yeni Saç 225",
    "LSC Yeni Saç 226",
    "LSC Yeni Saç 227",
    "LSC Yeni Saç 228",
    "LSC Yeni Saç 229",
    "LSC Yeni Saç 230",
    "LSC Yeni Saç 231",
    "LSC Yeni Saç 232",
    "LSC Yeni Saç 233",
    "LSC Yeni Saç 234",
    "LSC Yeni Saç 235",
    "LSC Yeni Saç 236",
    "LSC Yeni Saç 237",
    "LSC Yeni Saç 238",
    "LSC Yeni Saç 239",
    "LSC Yeni Saç 240",
    "LSC Yeni Saç 241",
    "LSC Yeni Saç 242",
    "LSC Yeni Saç 243",
    "LSC Yeni Saç 244",
    "LSC Yeni Saç 245",
    "LSC Yeni Saç 246",
    "LSC Yeni Saç 247",
    "LSC Yeni Saç 248",
    "LSC Yeni Saç 249",
    "LSC Yeni Saç 250",
    "LSC Yeni Saç 251",
    "LSC Yeni Saç 252",
    "LSC Yeni Saç 253",
    "LSC Yeni Saç 254",
    "LSC Yeni Saç 255",
    "LSC Yeni Saç 256",
    "LSC Yeni Saç 257",
    "LSC Yeni Saç 258",
    "LSC Yeni Saç 259",
    "LSC Yeni Saç 260",
    "LSC Yeni Saç 261",
    "LSC Yeni Saç 262",
    "LSC Yeni Saç 263",
    "LSC Yeni Saç 264",
    "LSC Yeni Saç 265",
    "LSC Yeni Saç 266",
    "LSC Yeni Saç 267",
    "LSC Yeni Saç 268",
    "LSC Yeni Saç 269",
    "LSC Yeni Saç 270",
    "LSC Yeni Saç 271",
    "LSC Yeni Saç 272",
    "LSC Yeni Saç 273",
    "LSC Yeni Saç 274",
    "LSC Yeni Saç 275",
    "LSC Yeni Saç 276",
    "LSC Yeni Saç 277",
    "LSC Yeni Saç 278",
    "LSC Yeni Saç 279",
    "LSC Yeni Saç 280",
    "LSC Yeni Saç 281",
    "LSC Yeni Saç 282",
    "LSC Yeni Saç 283",
    "LSC Yeni Saç 284",
    "LSC Yeni Saç 285",
    "LSC Yeni Saç 286",
    "LSC Yeni Saç 287",
    "LSC Yeni Saç 288",
    "LSC Yeni Saç 289",
    "LSC Yeni Saç 290",
    "LSC Yeni Saç 291",
    "LSC Yeni Saç 292",
    "LSC Yeni Saç 293",
    "LSC Yeni Saç 294",
    "LSC Yeni Saç 295",
    "LSC Yeni Saç 296",
    "LSC Yeni Saç 297",
    "LSC Yeni Saç 298",
    "LSC Yeni Saç 299",
    "LSC Yeni Saç 300",
    "LSC Yeni Saç 301",
    "LSC Yeni Saç 302",
    "LSC Yeni Saç 303",
    "LSC Yeni Saç 304",
    "LSC Yeni Saç 305",
    "LSC Yeni Saç 306",
    "LSC Yeni Saç 307",
    "LSC Yeni Saç 308",
    "LSC Yeni Saç 309",
    "LSC Yeni Saç 310",
    "LSC Yeni Saç 311",
    "LSC Yeni Saç 312",
    "LSC Yeni Saç 313",
    "LSC Yeni Saç 314",
    "LSC Yeni Saç 315",
    "LSC Yeni Saç 316",
    "LSC Yeni Saç 317",
    "LSC Yeni Saç 318",
    "LSC Yeni Saç 319",
    "LSC Yeni Saç 320",
    "LSC Yeni Saç 321",
    "LSC Yeni Saç 322",
    "LSC Yeni Saç 323",
    "LSC Yeni Saç 324",
    "LSC Yeni Saç 325",
    "LSC Yeni Saç 326",
    "LSC Yeni Saç 327",
    "LSC Yeni Saç 328",
    "LSC Yeni Saç 329",
    "LSC Yeni Saç 330",
    "LSC Yeni Saç 331",
    "LSC Yeni Saç 332",
    "LSC Yeni Saç 333",
    "LSC Yeni Saç 334",
    "LSC Yeni Saç 335",
    "LSC Yeni Saç 336",
    "LSC Yeni Saç 337",
    "LSC Yeni Saç 338",
    "LSC Yeni Saç 339",
    "LSC Yeni Saç 340",
    "LSC Yeni Saç 341",
    "LSC Yeni Saç 342",
    "LSC Yeni Saç 343",
    "LSC Yeni Saç 344",
    "LSC Yeni Saç 345",
    "LSC Yeni Saç 346",
    "LSC Yeni Saç 347",
    "LSC Yeni Saç 348",
    "LSC Yeni Saç 349",
];
const femaleHair = [
    'Kel',
    'Kısa Saç 1',
    'Kısa Saç 2',
    'Çift Örgülü Saç',
    'At Kuyruğu',
    'Kıvırcık Kısa Saç',
    'Rasta Saç 1',
    'Küt Saç Modeli',
    'Kısa Saç 4',
    'Kısa Saç 5',
    'Küt Saç Modeli 2',
    'Topuz Saç 1',
    'Kısa Saç 7',
    'Kısa Saç 8',
    'Topuz Saç 2',
    'Dalgalı Saç',
    'Dalgalı Toplanmış Saç',
    'Topuz Saç 3',
    'Kızıl Derili Saç Modeli',
    'Topuz Saç 4',
    'Kıvırcık Açık Saç',
    'Kıvırcık Kısa Saç',
    'Rasta Topuz Saç',
    'Presley Saç Modeli 1',
    'Presley Saç Modeli 2',
    'Kısa Rasta Saç 1',
    'Kısa Rasta Saç 2',
    'Kısa Rasta Saç 3',
    'İkili Salaş Örgü',
    'Yıldız Rasta Saç Modeli',
    'Merkez Rasta Saç Modeli',
    'Dağınık Uzun Topuz Saç',
    'Kısa Saç 9',
    'Traşlı Kısa Saç',
    'Traşlı Kısa Saç 2',
    'Diken Saç Modeli',
    'İkili Salaş Örgü ve Bandana',
    'Traşlı Kıza Saç 3',
    'Kısa Saç 10',
    'Kısa Saç 11',
    'Kısa Saç 2',
    'Çift Örgülü Saç',
    'At Kuyruğu',
    'Kıvırcık Kısa Saç',
    'Rasta Saç 1',
    'Kısa Saç 3',
    'Kısa Saç 4',
    'Kısa Saç 5',
    'Kısa Saç 6',
    'Topuz Saç 1',
    'Kısa Saç 7',
    'Kısa Saç 8',
    'Topuz Saç 2',
    'Dalgalı Saç',
    'Dalgalı Toplanmış Saç',
    'Topuz Saç 3',
    'Kızıl Derili Saç Modeli',
    'Topuz Saç 4',
    'Kıvırcık Açık Saç',
    'Kıvırcık Kısa Saç',
    'Rasta Topuz Saç',
    'Presley Saç Modeli 1',
    'Presley Saç Modeli 2',
    'Kısa Rasta Saç 1',
    'Kısa Rasta Saç 2',
    'Kısa Rasta Saç 3',
    'İkili Salaş Örgü',
    'Yıldız Rasta Saç Modeli',
    'Merkez Rasta Saç Modeli',
    'Dağınık Uzun Topuz Saç',
    'Kısa Saç 9',
    'Traşlı Kısa Saç',
    'Traşlı Kısa Saç 2',
    'Diken Saç Modeli',
    'İkili Salaş Örgü ve Bandana',
    'Traşlı Kıza Saç 3',
    'Topuz 5',
    'Kısa Saç 12',
    'Traşlı Kel',
    'LSC Yeni Saç 1',
    'LSC Yeni Saç 2',
    'LSC Yeni Saç 3',
    'LSC Yeni Saç 4',
    'LSC Yeni Saç 5',
    'LSC Yeni Saç 6',
    'LSC Yeni Saç 7',
    'LSC Yeni Saç 8',
    'LSC Yeni Saç 9',
    'LSC Yeni Saç 10',
    'LSC Yeni Saç 11',
    'LSC Yeni Saç 12',
    'LSC Yeni Saç 13',
    'LSC Yeni Saç 14',
    'LSC Yeni Saç 15',
    'LSC Yeni Saç 16',
    'LSC Yeni Saç 17',
    'LSC Yeni Saç 18',
    'LSC Yeni Saç 19',
    'LSC Yeni Saç 20',
    'LSC Yeni Saç 21',
    'LSC Yeni Saç 22',
    'LSC Yeni Saç 23',
    'LSC Yeni Saç 24',
    'LSC Yeni Saç 25',
    'LSC Yeni Saç 26',
    'LSC Yeni Saç 27',
    'LSC Yeni Saç 28',
    'LSC Yeni Saç 29',
    'LSC Yeni Saç 30',
    'LSC Yeni Saç 31',
    'LSC Yeni Saç 32',
    'LSC Yeni Saç 33',
    'LSC Yeni Saç 34',
    'LSC Yeni Saç 35',
    'LSC Yeni Saç 36',
    'LSC Yeni Saç 37',
    'LSC Yeni Saç 38',
    'LSC Yeni Saç 39',
    'LSC Yeni Saç 40',
    'LSC Yeni Saç 41',
    'LSC Yeni Saç 42',
    'LSC Yeni Saç 43',
    'LSC Yeni Saç 44',
    'LSC Yeni Saç 45',
    'LSC Yeni Saç 46',
    'LSC Yeni Saç 47',
    'LSC Yeni Saç 48',
    'LSC Yeni Saç 49',
    'LSC Yeni Saç 50',
    'LSC Yeni Saç 51',
    'LSC Yeni Saç 52',
    'LSC Yeni Saç 53',
    'LSC Yeni Saç 54',
    'LSC Yeni Saç 55',
    'LSC Yeni Saç 56',
    'LSC Yeni Saç 57',
    'LSC Yeni Saç 58',
    'LSC Yeni Saç 59',
    'LSC Yeni Saç 60',
    'LSC Yeni Saç 61',
    'LSC Yeni Saç 62',
    'LSC Yeni Saç 63',
    'LSC Yeni Saç 64',
    'LSC Yeni Saç 65',
    'LSC Yeni Saç 66',
    'LSC Yeni Saç 67',
    'LSC Yeni Saç 68',
    'LSC Yeni Saç 69',
    'LSC Yeni Saç 70',
    'LSC Yeni Saç 71',
    'LSC Yeni Saç 72',
    'LSC Yeni Saç 73',
    'LSC Yeni Saç 74',
    'LSC Yeni Saç 75',
    'LSC Yeni Saç 76',
    'LSC Yeni Saç 77',
    'LSC Yeni Saç 78',
    'LSC Yeni Saç 79',
    'LSC Yeni Saç 80',
    'LSC Yeni Saç 81',
    'LSC Yeni Saç 82',
    'LSC Yeni Saç 83',
    'LSC Yeni Saç 84',
    'LSC Yeni Saç 85',
    'LSC Yeni Saç 86',
    'LSC Yeni Saç 87',
    'LSC Yeni Saç 88',
    'LSC Yeni Saç 89',
    'LSC Yeni Saç 90',
    'LSC Yeni Saç 91',
    'LSC Yeni Saç 92',
    'LSC Yeni Saç 93',
    'LSC Yeni Saç 94',
    'LSC Yeni Saç 95',
    'LSC Yeni Saç 96',
    'LSC Yeni Saç 97',
    'LSC Yeni Saç 98',
    'LSC Yeni Saç 99',
    'LSC Yeni Saç 100',
    'LSC Yeni Saç 101',
    'LSC Yeni Saç 102',
    'LSC Yeni Saç 103',
    'LSC Yeni Saç 104',
    'LSC Yeni Saç 105',
    'LSC Yeni Saç 106',
    'LSC Yeni Saç 107',
    'LSC Yeni Saç 108',
    'LSC Yeni Saç 109',
    'LSC Yeni Saç 110',
    'LSC Yeni Saç 111',
    'LSC Yeni Saç 112',
    'LSC Yeni Saç 113',
    'LSC Yeni Saç 114',
    'LSC Yeni Saç 115',
    'LSC Yeni Saç 116',
    'LSC Yeni Saç 117',
    'LSC Yeni Saç 118',
    'LSC Yeni Saç 119',
    'LSC Yeni Saç 120',
    'LSC Yeni Saç 121',
    'LSC Yeni Saç 122',
    'LSC Yeni Saç 123',
    'LSC Yeni Saç 124',
    'LSC Yeni Saç 125',
    'LSC Yeni Saç 126',
    'LSC Yeni Saç 127', 
    'LSC Yeni Saç 128',
    'LSC Yeni Saç 129',
    "LSC Yeni Saç 130",
    "LSC Yeni Saç 131",
    "LSC Yeni Saç 132",
    "LSC Yeni Saç 133",
    "LSC Yeni Saç 134",
    "LSC Yeni Saç 135",
    "LSC Yeni Saç 136",
    "LSC Yeni Saç 137",
    "LSC Yeni Saç 138",
    "LSC Yeni Saç 139",
    "LSC Yeni Saç 140",
    "LSC Yeni Saç 141",
    "LSC Yeni Saç 142",
    "LSC Yeni Saç 143",
    "LSC Yeni Saç 144",
    "LSC Yeni Saç 145",
    "LSC Yeni Saç 146",
    "LSC Yeni Saç 147",
    "LSC Yeni Saç 148",
    "LSC Yeni Saç 149",
    "LSC Yeni Saç 150",
    "LSC Yeni Saç 151",
    "LSC Yeni Saç 152",
    "LSC Yeni Saç 153",
    "LSC Yeni Saç 154",
    "LSC Yeni Saç 155",
    "LSC Yeni Saç 156",
    "LSC Yeni Saç 157",
    "LSC Yeni Saç 158",
    "LSC Yeni Saç 159",
    "LSC Yeni Saç 160",
    "LSC Yeni Saç 161",
    "LSC Yeni Saç 162",
    "LSC Yeni Saç 163",
    "LSC Yeni Saç 164",
    "LSC Yeni Saç 165",
    "LSC Yeni Saç 166",
    "LSC Yeni Saç 167",
    "LSC Yeni Saç 168",
    "LSC Yeni Saç 169",
    "LSC Yeni Saç 170",
    "LSC Yeni Saç 171",
    "LSC Yeni Saç 172",
    "LSC Yeni Saç 173",
    "LSC Yeni Saç 174",
    "LSC Yeni Saç 175",
    "LSC Yeni Saç 176",
    "LSC Yeni Saç 177",
    "LSC Yeni Saç 178",
    "LSC Yeni Saç 179",
    "LSC Yeni Saç 180",
    "LSC Yeni Saç 181",
    "LSC Yeni Saç 182",
    "LSC Yeni Saç 183",
    "LSC Yeni Saç 184",
    "LSC Yeni Saç 185",
    "LSC Yeni Saç 186",
    "LSC Yeni Saç 187",
    "LSC Yeni Saç 188",
    "LSC Yeni Saç 189",
    "LSC Yeni Saç 190",
    "LSC Yeni Saç 191",
    "LSC Yeni Saç 192",
    "LSC Yeni Saç 193",
    "LSC Yeni Saç 194",
    "LSC Yeni Saç 195",
    "LSC Yeni Saç 196",
    "LSC Yeni Saç 197",
    "LSC Yeni Saç 198",
    "LSC Yeni Saç 199",
    "LSC Yeni Saç 200",
    "LSC Yeni Saç 201",
    "LSC Yeni Saç 202",
    "LSC Yeni Saç 203",
    "LSC Yeni Saç 204",
    "LSC Yeni Saç 205",
    "LSC Yeni Saç 206",
    "LSC Yeni Saç 207",
    "LSC Yeni Saç 208",
    "LSC Yeni Saç 209",
    "LSC Yeni Saç 210",
    "LSC Yeni Saç 211",
    "LSC Yeni Saç 212",
    "LSC Yeni Saç 213",
    "LSC Yeni Saç 214",
    "LSC Yeni Saç 215",
    "LSC Yeni Saç 216",
    "LSC Yeni Saç 217",
    "LSC Yeni Saç 218",
    "LSC Yeni Saç 219",
    "LSC Yeni Saç 220",
    "LSC Yeni Saç 221",
    "LSC Yeni Saç 222",
    "LSC Yeni Saç 223",
    "LSC Yeni Saç 224",
    "LSC Yeni Saç 225",
    "LSC Yeni Saç 226",
    "LSC Yeni Saç 227",
    "LSC Yeni Saç 228",
    "LSC Yeni Saç 229",
    "LSC Yeni Saç 230",
    "LSC Yeni Saç 231",
    "LSC Yeni Saç 232",
    "LSC Yeni Saç 233",
    "LSC Yeni Saç 234",
    "LSC Yeni Saç 235",
    "LSC Yeni Saç 236",
    "LSC Yeni Saç 237",
    "LSC Yeni Saç 238",
    "LSC Yeni Saç 239",
    "LSC Yeni Saç 240",
    "LSC Yeni Saç 241",
    "LSC Yeni Saç 242",
    "LSC Yeni Saç 243",
    "LSC Yeni Saç 244",
    "LSC Yeni Saç 245",
    "LSC Yeni Saç 246",
    "LSC Yeni Saç 247",
    "LSC Yeni Saç 248",
    "LSC Yeni Saç 249",
    "LSC Yeni Saç 250",
    "LSC Yeni Saç 251",
    "LSC Yeni Saç 252",
    "LSC Yeni Saç 253",
    "LSC Yeni Saç 254",
    "LSC Yeni Saç 255",
    "LSC Yeni Saç 256",
    "LSC Yeni Saç 257",
    "LSC Yeni Saç 258",
    "LSC Yeni Saç 259",
    "LSC Yeni Saç 260",
    "LSC Yeni Saç 261",
    "LSC Yeni Saç 262",
    "LSC Yeni Saç 263",
    "LSC Yeni Saç 264",
    "LSC Yeni Saç 265",
    "LSC Yeni Saç 266",
    "LSC Yeni Saç 267",
    "LSC Yeni Saç 268",
    "LSC Yeni Saç 269",
    "LSC Yeni Saç 270",
    "LSC Yeni Saç 271",
    "LSC Yeni Saç 272",
    "LSC Yeni Saç 273",
    "LSC Yeni Saç 274",
    "LSC Yeni Saç 275",
    "LSC Yeni Saç 276",
    "LSC Yeni Saç 277",
    "LSC Yeni Saç 278",
    "LSC Yeni Saç 279",
    "LSC Yeni Saç 280",
    "LSC Yeni Saç 281",
    "LSC Yeni Saç 282",
    "LSC Yeni Saç 283",
    "LSC Yeni Saç 284",
    "LSC Yeni Saç 285",
    "LSC Yeni Saç 286",
    "LSC Yeni Saç 287",
    "LSC Yeni Saç 288",
    "LSC Yeni Saç 289",
    "LSC Yeni Saç 290",
    "LSC Yeni Saç 291",
    "LSC Yeni Saç 292",
    "LSC Yeni Saç 293",
    "LSC Yeni Saç 294",
    "LSC Yeni Saç 295",
    "LSC Yeni Saç 296",
    "LSC Yeni Saç 297",
    "LSC Yeni Saç 298",
    "LSC Yeni Saç 299",
    "LSC Yeni Saç 300",
    "LSC Yeni Saç 301",
    "LSC Yeni Saç 302",
    "LSC Yeni Saç 303",
    "LSC Yeni Saç 304",
    "LSC Yeni Saç 305",
    "LSC Yeni Saç 306",
    "LSC Yeni Saç 307",
    "LSC Yeni Saç 308",
    "LSC Yeni Saç 309",
    "LSC Yeni Saç 310",
    "LSC Yeni Saç 311",
    "LSC Yeni Saç 312",
    "LSC Yeni Saç 313",
    "LSC Yeni Saç 314",
    "LSC Yeni Saç 315",
    "LSC Yeni Saç 316",
    "LSC Yeni Saç 317",
    "LSC Yeni Saç 318",
    "LSC Yeni Saç 319",
    "LSC Yeni Saç 320",
    "LSC Yeni Saç 321",
    "LSC Yeni Saç 322",
    "LSC Yeni Saç 323",
    "LSC Yeni Saç 324",
    "LSC Yeni Saç 325",
    "LSC Yeni Saç 326",
    "LSC Yeni Saç 327",
    "LSC Yeni Saç 328",
    "LSC Yeni Saç 329",
    "LSC Yeni Saç 330",
    "LSC Yeni Saç 331",
    "LSC Yeni Saç 332",
    "LSC Yeni Saç 333",
    "LSC Yeni Saç 334",
    "LSC Yeni Saç 335",
    "LSC Yeni Saç 336",
    "LSC Yeni Saç 337",
    "LSC Yeni Saç 338",
    "LSC Yeni Saç 339",
    "LSC Yeni Saç 340",
    "LSC Yeni Saç 341",
    "LSC Yeni Saç 342",
    "LSC Yeni Saç 343",
    "LSC Yeni Saç 344",
    "LSC Yeni Saç 345",
    "LSC Yeni Saç 346",
    "LSC Yeni Saç 347",
    "LSC Yeni Saç 348",
    "LSC Yeni Saç 349",
];
const hairColors = [
    'Siyah',
    'Açık Siyah',
    'Açık Siyah 2',
    'Koyu Kahverengi 1',
    'Kahverengi',
    'Açık Kahverengi',
    'Açık Kahverengi 2',
    'Açık Kahverengi 3',
    'Açık Kahverengi 4',
    'Sarışın 1',
    'Sarışın 2',
    'Sarışın 3',
    'Sarışın 4',
    'Sarışın 5',
    'Sarışın 6',
    'Sarışın 7',
    'Sarışın 8',
    'Kızıl 1',
    'Kızıl 2',
    'Kırmızı 1',
    'Kırmızı 2',
    'Kırmızı 3',
    'Kırmızı 4',
    'Kızıl 3',
    'Kızıl 4',
    'Kızıl 5',
    'Gri',
    'Gri 2',
    'Kül Rengi',
    'Kül Rengi 2',
    'Mor',
    'Açık Mor',
    'Pembe',
    'Açık Pembe',
    'Açık Pembe 2',
    'Aslan Ağzı',
    'Cam Göbeği',
    'Koyu Cam Göbeği',
    'Lacivert',
    'Yeşil',
    'Zümrüt',
    'Koyu Zümrüt',
    'Fıstık Yeşili',
    'Açık Fıstık Yeşili',
    'Koyu Yeşil',
    'Sarı',
    'Altın Sarısı',
    'Turuncu',
    'Açık Turuncu',
    'Koyu Turuncu',
    'Koyu Turuncu 2',
    'Koyu Turuncu 3',
    'Kırmızı 5',
    'Açık Kızıl',
    'Koyu Kızıl',
    'Koyu Kahverengi 2',
    'Koyu Kahverengi 3',
    'Koyu Kahverengi 4',
    'Koyu Kahverengi 5',
    'Koyu Kahverengi 6'
];
const facialHair = [
    'Kirli Sakal',
    'Kirli Top Sakal',
    'Top Sakal',
    'Çene ve Bıyık',
    'Çene Modeli',
    'Yaygın Çene',
    'İnce Yan Sakal',
    'Kirli Sakal 2',
    'Bıyık ve Çene Kemği',
    'Bıyık',
    'Yoğun Sakal 1',
    'Kirli Yoğun Sakal',
    'İnce Top Sakal',
    'Traşlı Kirli Sakal',
    'Traşlı Yoğun Sakal',
    'Traşlı Yan Sakal',
    'Favori ve Top Sakal',
    'Kirli Favori',
    'Yoğun Sakal 2',
    'Eski tip Bıyık',
    'Eski tip Bıyık ve Kirli Sakal',
    'Geniş Bıyık',
    'Bıyık ve Diken',
    'Eski Bıyık ve Sakal',
    'Eski bıyık ve Kirli Sakal',
    'Uzun Bıyık',
    'The Hampstead',
    'Favori ve Bıyık',
    'Asker Sakalı',
    'Alt Sakal',
    'LSC Yeni Sakal 1',
    'LSC Yeni Sakal 2',
    'LSC Yeni Sakal 3',
    'LSC Yeni Sakal 4',
    'LSC Yeni Sakal 5',
    'LSC Yeni Sakal 6',
    'LSC Yeni Sakal 7',
    'LSC Yeni Sakal 8',
    'LSC Yeni Sakal 9',
    'LSC Yeni Sakal 10',
    'LSC Yeni Sakal 11',
    'LSC Yeni Sakal 12',
    'LSC Yeni Sakal 13', 
];
const overlayColors = [
    'Red',
    'Pink',
    'Light Pink',
    'Lighter Pink',
    'Lightest Pink',
    'Light Maroon',
    'Maroon',
    'Light Brown',
    'Lighter Brown',
    'Lightest Brown',
    'White Pink',
    'Beige',
    'Brown Red',
    'Orange',
    'Orange Pink',
    'Lightest Pink',
    'Lighter Pink',
    'Pink',
    'Vibrant Pink',
    'Dark Pink',
    'Darker Pink',
    'Darkest Pink',
    'Red',
    'Lighter Red',
    'Vibrant Red',
    'Red Pink',
    'Purple',
    'Light Purple',
    'Dark Purple',
    'Darker Purple',
    'Darkest Purple',
    'Vibrant Purple',
    'Black Purple',
    'Blue',
    'Light Blue',
    'Lighter Blue',
    'Lightest Blue',
    'Cyan',
    'Sea Green',
    'Deep Sea Green',
    'Green',
    'Dark Green',
    'Light Green',
    'Yellow Green',
    'Dark Yellow',
    'Yellow',
    'Yellow Orange',
    'Dark Yellow Orange',
    'Vigrant Orange',
    'Dark Orange',
    'Blonde',
    'Blonde White',
    'White',
    'Gray',
    'Dark Gray',
    'Darkest Gray',
    'Black',
    'Light Blue',
    'Dark Blue',
    'Darkest Blue',
    'Light Brown',
    'Brown',
    'Dark Brown',
    'Darker Brown'
];
const eyebrowNames = [
    'Kaş 1',
    'Kaş 2',
    'Kaş 3',
    'Kaş 4',
    'Kaş 5',
    'Kaş 6',
    'Kaş 7',
    'Kaş 8',
    'Kaş 9',
    'Kaş 10',
    'Kaş 11',
    'Kaş 12',
    'Kaş 13',
    'Kaş 14',
    'Kaş 15',
    'Kaş 16',
    'Kaş 17',
    'Kaş 18',
    'Kaş 19',
    'Kaş 20',
    'Kaş 21',
    'Kaş 22',
    'Kaş 23',
    'Kaş 24',
    'Kaş 25',
    'Kaş 26',
    'Kaş 27',
    'Kaş 28',
    'Kaş 29',
    'Kaş 30',
    'Kaş 31',
    'Kaş 32',
    'Kaş 33',
    'Kaş 34',
    'Kaş 35',
    'None'
];
