const maleHair = [
    'Kel',
    'Kısa Saç 1',
    'Kısa Saç 2',
    'Traşlı Kısa Saç 1',
    'Kısa Saç 3',
    'Dağınık Kısa Saç',
    'Dağınık Traşlı Saç',
    'At Kuyruğu',
    'Rasta Saç Modeli 1',
    'Kıvırcık Kıas Saç',
    'Kısa Saç 4',
    'Kısa Dik Saç',
    'Kısa Saç 5',
    'Dağınık Uzun Saç 1',
    'Rasta Uzun Saç',
    'Düz Uzun Saç 1',
    'Kıvırcık Uzun Saç',
    'Düz Uzun Saç 2',
    'Kısa Saç 6',
    'Düz Uzun Saç 2',
    'Traşlı Kısa Saç',
    'Presley Saç Modeli 1',
    'Presley Saç Modeli 2',
    'Presley Saç Modeli 3',
    'Rasta Saç Modeli 2',
    'Rasta Saç Modeli 3',
    'Rasta Saç Modeli 3',
    'Rasta Saç Modeli 4',
    'Rasta Saç Modeli 5',
    'Rasta Saç Modeli 6',
    'Kısa Presley Modeli',
    'Orta Uzun Saç',
    'Traşlı Kısa Saç 2',
    'Traşlı Kısa Saç 3',
    'Diken Modeli Saç',
    'Dağınık Uzun Saç 2',
    'Ayrımlı Uzun Saç',
    'Kısa Saç 1',
    'Kısa Saç 2',
    'Traşlı Kısa Saç 1',
    'Kısa Saç 3',
    'Dağınık Kısa Saç',
    'Dağınık Traşlı Saç',
    'At Kuyruğu',
    'Rasta Saç Modeli 1',
    'Kıvırcık Kıas Saç',
    'Kısa Saç 4',
    'Kısa Dik Saç',
    'Kısa Saç 5',
    'Dağınık Uzun Saç 1',
    'Rasta Saç Modeli 1',
    'Ayrımlı Uzun Saç 2',
    'Kıvırcık Saç Modeli',
    'Uzun Saç 2',
    'Kısa Saç 6',
    'Kısa Saç 7',
    'Uzun Saç 3',
    'Traşlı Kısa Saç 2',
    'Presley Saç Modeli',
    'Rasta Saç Modeli 2',
    'Rasta Saç Modeli 3',
    'Rasta Saç Modeli 4',
    'Rasta Saç Modeli 5',
    'Rasta Saç Modeli 6',
    'Rasta Saç Modeli 7',
    'Presley Modeli 2',
    'Uzun Saç 4',
    'Traşlı Kısa Saç 2',
    'Traşlı Kısa Saç 3',
    'Mohawk',
    'Diken Saç Modeli',
    'Dağınık Uzun Saç',
    'Ayrımlı Uzun Saç 2',
    'Dik Kısa Saç 2',
    'Traşlı Kısa Saç 4'
];
const femaleHair = [
    'Kel',
    'Kısa Saç 1',
    'Kısa Saç 2',
    'Çift Örgülü Saç',
    'At Kuyruğu',
    'Kıvırcık Kısa Saç',
    'Rasta Saç 1',
    'Küt Saç Modeli',
    'Kısa Saç 4',
    'Kısa Saç 5',
    'Küt Saç Modeli 2',
    'Topuz Saç 1',
    'Kısa Saç 7',
    'Kısa Saç 8',
    'Topuz Saç 2',
    'Dalgalı Saç',
    'Dalgalı Toplanmış Saç',
    'Topuz Saç 3',
    'Kızıl Derili Saç Modeli',
    'Topuz Saç 4',
    'Kıvırcık Açık Saç',
    'Kıvırcık Kısa Saç',
    'Rasta Topuz Saç',
    'Presley Saç Modeli 1',
    'Presley Saç Modeli 2',
    'Kısa Rasta Saç 1',
    'Kısa Rasta Saç 2',
    'Kısa Rasta Saç 3',
    'İkili Salaş Örgü',
    'Yıldız Rasta Saç Modeli',
    'Merkez Rasta Saç Modeli',
    'Dağınık Uzun Topuz Saç',
    'Kısa Saç 9',
    'Traşlı Kısa Saç',
    'Traşlı Kısa Saç 2',
    'Diken Saç Modeli',
    'İkili Salaş Örgü ve Bandana',
    'Traşlı Kıza Saç 3',
    'Kısa Saç 10',
    'Kısa Saç 11',
    'Kısa Saç 2',
    'Çift Örgülü Saç',
    'At Kuyruğu',
    'Kıvırcık Kısa Saç',
    'Rasta Saç 1',
    'Kısa Saç 3',
    'Kısa Saç 4',
    'Kısa Saç 5',
    'Kısa Saç 6',
    'Topuz Saç 1',
    'Kısa Saç 7',
    'Kısa Saç 8',
    'Topuz Saç 2',
    'Dalgalı Saç',
    'Dalgalı Toplanmış Saç',
    'Topuz Saç 3',
    'Kızıl Derili Saç Modeli',
    'Topuz Saç 4',
    'Kıvırcık Açık Saç',
    'Kıvırcık Kısa Saç',
    'Rasta Topuz Saç',
    'Presley Saç Modeli 1',
    'Presley Saç Modeli 2',
    'Kısa Rasta Saç 1',
    'Kısa Rasta Saç 2',
    'Kısa Rasta Saç 3',
    'İkili Salaş Örgü',
    'Yıldız Rasta Saç Modeli',
    'Merkez Rasta Saç Modeli',
    'Dağınık Uzun Topuz Saç',
    'Kısa Saç 9',
    'Traşlı Kısa Saç',
    'Traşlı Kısa Saç 2',
    'Diken Saç Modeli',
    'İkili Salaş Örgü ve Bandana',
    'Traşlı Kıza Saç 3',
    'Topuz 5',
    'Kısa Saç 12',
    'Elvis (Erkek Karakterler İçin)'
];
const hairColors = [
    'Siyah',
    'Açık Siyah',
    'Açık Siyah 2',
    'Koyu Kahverengi 1',
    'Kahverengi',
    'Açık Kahverengi',
    'Açık Kahverengi 2',
    'Açık Kahverengi 3',
    'Açık Kahverengi 4',
    'Sarışın 1',
    'Sarışın 2',
    'Sarışın 3',
    'Sarışın 4',
    'Sarışın 5',
    'Sarışın 6',
    'Sarışın 7',
    'Sarışın 8',
    'Kızıl 1',
    'Kızıl 2',
    'Kırmızı 1',
    'Kırmızı 2',
    'Kırmızı 3',
    'Kırmızı 4',
    'Kızıl 3',
    'Kızıl 4',
    'Kızıl 5',
    'Gri',
    'Gri 2',
    'Kül Rengi',
    'Kül Rengi 2',
    'Mor',
    'Açık Mor',
    'Pembe',
    'Açık Pembe',
    'Açık Pembe 2',
    'Aslan Ağzı',
    'Cam Göbeği',
    'Koyu Cam Göbeği',
    'Lacivert',
    'Yeşil',
    'Zümrüt',
    'Koyu Zümrüt',
    'Fıstık Yeşili',
    'Açık Fıstık Yeşili',
    'Koyu Yeşil',
    'Sarı',
    'Altın Sarısı',
    'Turuncu',
    'Açık Turuncu',
    'Koyu Turuncu',
    'Koyu Turuncu 2',
    'Koyu Turuncu 3',
    'Kırmızı 5',
    'Açık Kızıl',
    'Koyu Kızıl',
    'Koyu Kahverengi 2',
    'Koyu Kahverengi 3',
    'Koyu Kahverengi 4',
    'Koyu Kahverengi 5',
    'Koyu Kahverengi 6'
];
const facialHair = [
    'Kirli Sakal',
    'Kirli Top Sakal',
    'Top Sakal',
    'Çene ve Bıyık',
    'Çene Modeli',
    'Yaygın Çene',
    'İnce Yan Sakal',
    'Kirli Sakal 2',
    'Bıyık ve Çene Kemği',
    'Bıyık',
    'Yoğun Sakal 1',
    'Kirli Yoğun Sakal',
    'İnce Top Sakal',
    'Traşlı Kirli Sakal',
    'Traşlı Yoğun Sakal',
    'Traşlı Yan Sakal',
    'Favori ve Top Sakal',
    'Kirli Favori',
    'Yoğun Sakal 2',
    'Eski tip Bıyık',
    'Eski tip Bıyık ve Kirli Sakal',
    'Geniş Bıyık',
    'Bıyık ve Diken',
    'Eski Bıyık ve Sakal',
    'Eski bıyık ve Kirli Sakal',
    'Uzun Bıyık',
    'The Hampstead',
    'Favori ve Bıyık',
    'Asker Sakalı',
    'Alt Sakal'
];
const overlayColors = [
    'Red',
    'Pink',
    'Light Pink',
    'Lighter Pink',
    'Lightest Pink',
    'Light Maroon',
    'Maroon',
    'Light Brown',
    'Lighter Brown',
    'Lightest Brown',
    'White Pink',
    'Beige',
    'Brown Red',
    'Orange',
    'Orange Pink',
    'Lightest Pink',
    'Lighter Pink',
    'Pink',
    'Vibrant Pink',
    'Dark Pink',
    'Darker Pink',
    'Darkest Pink',
    'Red',
    'Lighter Red',
    'Vibrant Red',
    'Red Pink',
    'Purple',
    'Light Purple',
    'Dark Purple',
    'Darker Purple',
    'Darkest Purple',
    'Vibrant Purple',
    'Black Purple',
    'Blue',
    'Light Blue',
    'Lighter Blue',
    'Lightest Blue',
    'Cyan',
    'Sea Green',
    'Deep Sea Green',
    'Green',
    'Dark Green',
    'Light Green',
    'Yellow Green',
    'Dark Yellow',
    'Yellow',
    'Yellow Orange',
    'Dark Yellow Orange',
    'Vigrant Orange',
    'Dark Orange',
    'Blonde',
    'Blonde White',
    'White',
    'Gray',
    'Dark Gray',
    'Darkest Gray',
    'Black',
    'Light Blue',
    'Dark Blue',
    'Darkest Blue',
    'Light Brown',
    'Brown',
    'Dark Brown',
    'Darker Brown'
];
const eyebrowNames = [
    'Kaş 1',
    'Kaş 2',
    'Kaş 3',
    'Kaş 4',
    'Kaş 5',
    'Kaş 6',
    'Kaş 7',
    'Kaş 8',
    'Kaş 9',
    'Kaş 10',
    'Kaş 11',
    'Kaş 12',
    'Kaş 13',
    'Kaş 14',
    'Kaş 15',
    'Kaş 16',
    'Kaş 17',
    'Kaş 18',
    'Kaş 19',
    'Kaş 20',
    'Kaş 21',
    'Kaş 22',
    'Kaş 23',
    'Kaş 24',
    'Kaş 25',
    'Kaş 26',
    'Kaş 27',
    'Kaş 28',
    'Kaş 29',
    'Kaş 30',
    'Kaş 31',
    'Kaş 32',
    'Kaş 33',
    'Kaş 34',
    'Kaş 35',
    'None'
];
