import alt from 'alt';
import native from 'natives';

import {distance} from './utilities/vector.js';

let obj = [];

alt.onServer('Doors:Create', (range) => {
    let door;
    let doorCode;
    let canUse = true;
    doors.forEach(e => {
        if(canUse){
            door = native.getClosestObjectOfType(alt.Player.local.pos.x, alt.Player.local.pos.y, alt.Player.local.pos.z, range, alt.hash(e), false, 0, 0);
            doorCode = alt.hash(e); 
            if(door != 0){
                canUse = false;
                alt.emitServer('Doors:CreateCallBack', doorCode, alt.Player.local.pos.x, alt.Player.local.pos.y, alt.Player.local.pos.z, alt.Player.local.rot.x, alt.Player.local.rot.y, alt.Player.local.rot.z)
                //alt.emitServer('Doors:CreateCallBack', doorCode, door.pos.x, door.pos.y, alt.Player.local.rot.x, alt.Player.local.rot.y, alt.Player.local.rot.z)
                return;
            } 
        }        
    }) 
     
})

alt.onServer('Door:UpdateAll', (data) => {
    obj = JSON.parse(data);
    obj.forEach(e => {
        let newObj = {hash: e.hash, pos:{x: e.pos.X, y: e.pos.Y, z: e.pos.Z}, state: e.state};
        obj[e.textlblID] = newObj;
    })
})


alt.onServer('Door:Update', (data) => {
    let e = JSON.parse(data);
    obj[e.textlblID] = {hash: e.hash, pos:{x: e.pos.X, y: e.pos.Y, z: e.pos.Z}, state: e.state};
})

alt.setInterval(()=>{
    obj.forEach(e => {
        if(e){
            if(distance(alt.Player.local.pos, e.pos) < 20){
                native.doorControl(e.hash, e.pos.x, e.pos.y, e.pos.z, e.state, 0.0, 0.0, 0.0);
            }
        }
    });
}, 1000);




let doors = [
    "prop_door_balcony_frame",
    "ap1_02_door_l001",
    "ch3_04_pris08_top_door" ,
    "cs1_10_cable_door1",
    "vb_35_lifegaurddoor2" ,
    "prop_ron_door_01",
    "prop_out_door_speaker",
    "prop_bh1_44_door_01l" ,
    "bh1_44_door_left002" ,
    "prop_hw1_03_gardoor_01" ,
    "po1_sh1_port_xr_door09" ,
    "cs1_02_cfdoor_front_lod" ,
    "ap1_02_door_r001" ,
    "prop_outdoor_fan_01" ,
    "po1_sh1_port_xr_door02" ,
    "prop_car_door_04" ,
    "port_xr_lightdoor" ,
    "v_ilev_gc_door01"  ,
    "id2_14_predoor",
    "po1_sh1_port_xr_door00" ,
    "dt1_22_broken_gdoor_hd" ,
    "hw1_23_build2_door" ,
    "vb_43_door_l_mp" ,
    "bh1_44_door_right01",
    "hw1_02_door_blocker" ,
    "p_cut_door_01" ,
    "ch1_07_chopper_door" ,
    "po1_sh1_port_xr_door08" ,
    "sc1_00d_fencedoor"  ,
    "ch2_03c_removed_doors",
    "cs2_01_super_sidedoors",
    "prop_ss1_14_garage_door" ,
    "bh1_22_doorfizz_1" ,
    "prop_ch2_09c_garage_door" ,
    "prop_sm1_11_doorr" ,
    "prop_ch1_07_door_02r" ,
    "ch2_09b_hs02_door_railings" ,
    "prop_gar_door_03",
    "cs2_01_frdoor01" ,
    "prop_ss1_mpint_door_r" ,
    "hw1_13_garage_door_01" ,
    "prop_bh1_44_door_01r" ,
    "po1_sh1_port_xr_door13" ,
    "cs2_01_doorglass01" ,
    "prop_cs4_05_tdoor",
    "bh1_16_3_locked_doors" ,
    "v_ilev_bank4door02",
    "ch2_04_emissive_doors" ,
    "prop_ss1_mpint_door_l" ,
    "dt1_22_broken_gdoor_lod",
    "sm_19_doorcanopy_iref" ,
    "prop_mineshaft_door",
    "prop_container_door_mb_r" ,
    "prop_sm1_11_doorl" ,
    "prop_dt1_20_mp_door_r",
    "dt1_03_mp_door",
    "prop_damdoor_01" ,
    "po1_sh1_port_xr_door14",
    "ss1_11_meddoordtl",
    "dt1_06_hospitaldoor",
    "prop_ret_door_04" ,
    "po1_sh1_port_xr_door03" ,
    "prop_ss1_08_mp_door_r" ,
    "prop_bhhotel_door_r",
    "p_cut_door_02",
    "prop_gar_door_04" ,
    "port_xr_lightdoor",
    "ch2_04_emissive_doors_lod",
    "prop_kt1_10_mpdoor_r" ,
    "po1_sh1_rf_door004" ,
    "prop_ss1_10_door_l" ,
    "prop_container_door_mb_l" ,
    "v_ilev_bl_doorel_r" ,
    "prop_pris_door_03",
    "prop_car_door_01" ,
    "prop_ch1_07_door_01l" ,
    "prop_grumandoor_l",
    "hw1_02_grudoor_dummy" ,
    "prop_rub_busdoor_02" ,
    "prop_bhhotel_door_l" ,
    "port_xr_door_01",
    "prop_bhhotel_door_r" ,
    "hw1_01_doorblock",
    "prop_com_gar_door_01",
    "bh1_22_doorfizz_3" ,
    "cs1_02_cfdoor_slod" ,
    "po1_01_doorm" ,
    "prop_indus_meet_door_l" ,
    "prop_cntrdoor_ld_r" ,
    "ch3_01_trlrdoors_null",
    "prop_kt1_06_door_r" ,
    "prop_magenta_door" ,
    "prop_grumandoor_l" ,
    "prop_motel_door_09" ,
    "prop_gar_door_02" ,
    "cs4_02_sydoor004" ,
    "prop_ss1_10_door_r" ,
    "prop_dt1_20_mp_door_l",
    "dt1_19_roofdoor_dummy",
    "prop_ch3_04_door_01l",
    "prop_rub_busdoor_01" ,
    "v_ilev_fh_frntdoor" ,
    "prop_gar_door_04",
    "ap1_02_door_r",
    "v_ilev_bank4door01",
    "prop_ch3_04_door_01r" ,
    "prop_ch3_04_door_02" ,
    "plg_06_m2door_lod",
    "prop_kt1_10_mpdoor_l" ,
    "prop_map_door_01" ,
    "prop_magenta_door",
    "prop_rub_busdoor_02",
    "kt1_11_mp_door" ,
    "bh1_08_revolving_door_01" ,
    "prop_shop_front_door_r" ,
    "prop_bs_map_door_01" ,
    "prop_ch1_07_door_02l" ,
    "prop_gar_door_05" ,
    "po1_sh1_port_xr_door04" ,
    "prop_ss1_05_mp_door" ,
    "po1_sh1_port_xr_door11" ,
    "bh1_22_doorfizz_2" ,
    "prop_ch1_07_door_01r" ,
    "prop_cntrdoor_ld_l" ,
    "prop_sc1_12_door" ,
    "v_ilev_fh_frntdoor",
    "prop_com_gar_door_01" ,
    "port_xr_door_04",
    "prop_rub_busdoor_01",
    "hw1_02_gru_door_lod" ,
    "port_xr_lightdoor",
    "bh1_08_parkingdoor" ,
    "vb_43_door_l_mp",
    "po1_sh1_port_xr_door06" ,
    "prop_ch2_05d_g_door" ,
    "sm_14_mp_door_r" ,
    "port_xr_door_05",
    "po1_sh1_port_xr_door12" ,
    "plg_06_m2door"  ,
    "prop_shop_front_door_l" ,
    "prop_ron_door_01" ,
    "prop_car_door_01",
    "prop_cs4_11_door" ,
    "prop_sc1_21_g_door_01" ,
    "v_ilev_housedoor1" ,
    "prop_id_21_gardoor_01",
    "prop_car_door_03",
    "po1_sh1_port_xr_door07" ,
    "po1_sh1_port_xr_door01" ,
    "po1_06_props_gdoor_lod" ,
    "prop_gar_door_01" ,
    "ch2_07b_props_g_door_lod",
    "dt1_06_hospitaldoors_fixed",
    "prop_ch_025c_g_door_01",
    "prop_ss1_08_mp_door_l" ,
    "prop_sm_10_mp_door" ,
    "ss1_11_meddoordtl_lod" ,
    "prop_indus_meet_door_r" ,
    "port_xr_door_05" ,
    "bh1_44_door_left01" ,
    "sm_14_mp_door_l" ,
    "id1_13_props_doorslod" ,
    "bh1_22_door_det" ,
    "prop_a_trailer_door_01" ,
    "prop_pris_door_02",
    "prop_kt1_06_door_l",
    "ch3_01_trlrdoors_lod",
    "ss1_06b_backdoorcanopy",
    "prop_ch2_07b_20_g_door" ,
    "prop_grumandoor_r" ,
    "p_cut_door_03" ,
    "bh1_08_parkingdoor002" ,
    "v_ilev_bl_doorel_l" ,
    "cs3_07_towerdoor_dummy" ,
    "po1_sh1_port_xr_door05" ,
    "prop_car_door_03" ,
    "vb_43_door_r_mp" ,
    "ap1_02_door_l",
    "bh1_44_door_right002" ,
    "id2_14_predoor_lod",
    "po1_06_props_gdoor_slod" ,
    "port_xr_door_01" ,
    "po1_sh1_port_xr_door10" ,
    "prop_biolab_g_door" ,
    "cs1_02_cfdoor_side" ,
    "cs1_02_cfdoor_front" ,
    "prop_facgate_03_l",
    "sc1_02_spray_gates_03",
    "prop_cs_gravyard_gate_r",
    "prop_sec_barier_04b",
    "prop_facgate_03b_l",
    "prop_facgate_06_l",
    "prop_lrggate_01_l",
    "prop_fnclink_02gate6_r",
    "prop_lrggate_01_r",
    "prop_fnclink_09gate1",
    "prop_lrggate_05a",
    "prop_lrggate_03a",
    "bh1_47_gate_1_lod",
    "prop_sc1_06_gate_r",
    "prop_gate_docks_ld",
    "sm_27_gatec_002",
    "prop_fnclink_03gate5",
    "sm_24_irefgatea_01",
    "prop_lrggate_01c_l",
    "sc1_02_spray_gates_01",
    "prop_bh1_03_gate_l",
    "bh1_36_gatefrm_iref",
    "prop_fnclink_02gate5",
    "prop_facgate_01",
    "prop_facgate_03_r",
    "bh1_45_gate1",
    "prop_facgate_01b",,
    "prop_lrggate_01b",
    "prop_facgate_01b",
    "prop_fncres_06gatel",
    "prop_lrggate_01_r",
    "prop_sm_27_gate_04",
    "prop_bh1_48_gate_1",
    "prop_facgate_03b_r",
    "plg_06_gate_lod",
    "bh1_36_gate_iref",
    "prop_fnclink_02gate2",
    "prop_sec_gate_01d",
    "prop_facgate_08",
    "prop_fnclink_02gate7",
    "prop_fnclink_02gate6_l",
    "prop_sec_gate_01c",
    "prop_burto_gate_01",
    "prop_gate_airport_01",
    "po1_03_gate_lod",
    "prop_sc1_06_gate_l",
    "prop_bh1_03_gate_r",
    "prop_lrggate_02",
    "bh1_45_gate2",
    "prop_gate_prison_01",
    "prop_facgate_05_r",
    "sc1_27_gate_dnt_ex",
    "prop_gate_tep_01_r",
    "dt1_08_gate00",
    "prop_gate_cult_01_r",
    "prop_fnclink_02gate3",
    "prop_gate_tep_01_l",
    "prop_fncres_07gate",
    "sm_27_gateb_01",
    "prop_lrggate_03b_ld",
    "prop_facgate_04_r",
    "prop_gate_military_01",
    "prop_facgate_06_r",
    "prop_sm_27_gate",
    "cs3_07_mpgates_01",
    "prop_com_gar_door_01",
    "prop_lrggate_01_pst",
    "prop_lrggate_02_ld",
    "prop_lrggate_01c_r",
    "plg_03_ml_gate_01",
    "prop_fncwood_01gate",
    "bh1_31_gate",
    "bh1_47_gate_1",
    "bh1_47_gate_2_lod",
    "prop_fncres_08gatel",
    "ch2_12b_house_l1c_gate001",
    "bh1_47_gate_2",
    "sm_27_gateb_002",
    "prop_lrggate_04a",
    "sc1_02_spray_gates_02",
    "prop_facgate_04_l",
    "v_ilev_arm_secdoor",
    "v_ilev_ph_door01",
    "v_ilev_ph_door002",
    "prop_facgate_08",
    "v_ilev_ph_cellgate",
    "v_ilev_gtdoor",
    "prop_id2_11_gdoor",
    "prop_com_ls_door_01",
    "v_ilev_spraydoor",
    "lr_prop_supermod_door_01",
];